export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const GET_AUTOCOMPLETE_SEARCH_BEGIN = 'GET_AUTOCOMPLETE_SEARCH_BEGIN';
export const GET_AUTOCOMPLETE_SEARCH_SUCCESS = 'GET_AUTOCOMPLETE_SEARCH_SUCCESS';
export const GET_AUTOCOMPLETE_SEARCH_FAILURE = 'GET_AUTOCOMPLETE_SEARCH_FAILURE';

export const GET_FIVE_DAYS_FORECAST_BEGIN = 'GET_FIVE_DAYS_FORECAST_BEGIN';
export const GET_FIVE_DAYS_FORECAST_SUCCESS = 'GET_FIVE_DAYS_FORECAST_SUCCESS';
export const GET_FIVE_DAYS_FORECAST_FAILURE = 'GET_FIVE_DAYS_FORECAST_FAILURE';

export const GET_CURRENT_CONDITIONS_BEGIN = 'GET_CURRENT_CONDITIONS_BEGIN';
export const GET_CURRENT_CONDITIONS_SUCCESS = 'GET_CURRENT_CONDITIONS_SUCCESS';
export const GET_CURRENT_CONDITIONS_FAILURE = 'GET_CURRENT_CONDITIONS_FAILURE';

export const GET_MULTIPLE_CURRENT_CONDITIONS_BEGIN = 'GET_MULTIPLE_CURRENT_CONDITIONS_BEGIN';
export const GET_MULTIPLE_CURRENT_CONDITIONS_SUCCESS = 'GET_MULTIPLE_CURRENT_CONDITIONS_SUCCESS';
export const GET_MULTIPLE_CURRENT_CONDITIONS_FAILURE = 'GET_MULTIPLE_CURRENT_CONDITIONS_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';